Feature/moneyz enforce type check
resuelve/money pull request #4
Opened 2017-05-08 23:50 UTC by Creamen

- Enforce data type we can use for type moneyz for field
currency via a DOMAIN and a regex.
Now, moneyz.currency is two or three uppercase letters.
- Add IF EXISTS flag to DROP DOMAIN

2017-05-09 15:03 UTC, jordi-adame approved these changes

2017-05-09 16:55 UTC, oscarolbe requested changes

2017-05-09 16:55 UTC, oscarolbe commented on lib/money/ecto/moneyz_migration.ex
> +              CREATE DOMAIN rtd_currency_loose_type AS TEXT CHECK ( VALUE ~ '^[A-Z]{2,3}$' );
podemos llamarle currency_type o currency_loose_type, este proyecto no solo es para rtd

2017-05-09 17:34 UTC, alvarolizama commented on lib/money/ecto/moneyz_migration.ex
> +              CREATE DOMAIN rtd_currency_loose_type AS TEXT CHECK ( VALUE ~ '^[A-Z]{2,3}$' );
También se usa en la Tasa!

2017-05-09 17:47 UTC, Creamen commented on lib/money/ecto/moneyz_migration.ex
> +              CREATE DOMAIN rtd_currency_loose_type AS TEXT CHECK ( VALUE ~ '^[A-Z]{2,3}$' );
Si claro disculpe.
Yo hice los cambios y push esos.

2017-05-09 17:47 UTC, Creamen commented on lib/money/ecto/moneyz_migration.ex
> +              DROP DOMAIN IF EXISTS currency_loose_type;
@oscarolbe y @alvarolizama  :)

2017-05-09 17:52 UTC, alanraul approved these changes

2017-05-10 13:21 UTC, oscarolbe approved these changes

2017-05-10 13:21 UTC, merged