Formato para cantidades negativas
resuelve/money pull request #5
Opened 2017-12-19 00:22 UTC by nandoresuelve

Se agrega una nueva opción a la función _to_string_ ( negative_left ) que cuando son cantidades negativas coloca el signo de menos a la izquierda de $.

2017-12-19 00:35 UTC, oscarolbe requested changes

2017-12-19 00:35 UTC, oscarolbe commented on test/money_test.exs
> +    try do
El try no tiene caso, o si??

2017-12-19 00:36 UTC, oscarolbe commented on test/money_test.exs
> +    try do
ni aqui

2017-12-20 15:30 UTC, nandoresuelve commented on test/money_test.exs
> -    try do
@oscarolbe ya quité los bloques try del test :+1:

2017-12-20 16:07 UTC, oscarolbe approved these changes

2017-12-20 16:10 UTC, alvarolizama approved these changes

2017-12-20 16:10 UTC, merged